services:
  webwatchparty:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: watch
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=watch.gtgroup.dev
      - LETSENCRYPT_HOST=watch.gtgroup.dev
      - LETSENCRYPT_EMAIL=kupatadze2000@outlook.com
      - VIRTUAL_PORT=5000
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    restart: always

